export const DataList = [
    {
      id: 1,
      title: "GENESIS E-435 Gas Grill",
      category: "Gas-Grill",
      price: 15.99,
      img: "./assets/GasGrills/grill1.png",
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: "GENESIS E-325s Gas Grill (Natural Gas)",
      category: "Gas-Grill(NaturalGas)",
      price: 13.99,
      img: "./assets/GasGrills/grill2.png",
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: "GENESIS S-325s Gas Grill (Natural Gas)",
      category: "Gas-Grill(NaturalGas)",
      price: 6.99,
      img: "./assets/GasGrills/grill3.png",
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: "GENESIS E-335 Gas Grill (Natural Gas)",
      category: "Gas-Grill(NaturalGas)",
      price: 20.99,
      img: "./assets/GasGrills/grill4.png",
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: "GENESIS E-325s Gas Grill",
      category: "Gas-Grill",
      price: 22.99,
      img: "./assets/GasGrills/grill5.png",
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: "GENESIS S-335 Gas Grill",
      category: "Gas-Grill",
      price: 18.99,
      img: "./assets/GasGrills/grill6.png",
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: "GENESIS E-335 Gas Grill",
      category: "Gas-Grill",
      price: 8.99,
      img: "./assets/GasGrills/grill7.png",
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: "GENESIS E-335 Gas Grill",
      category: "Gas-Grill",
      price: 12.99,
      img: "./assets/GasGrills/grill8.png",
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: "Weber® Q 3200 Gas Grill",
      category: "Portable",
      price: 16.99,
      img: "./assets/GasGrills/grill9.png",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: "Weber® Q 2200 Gas Grill",
      category: "Portable",
      price: 22.99,
      img: "./assets/GasGrills/grill10.png",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 11,
      title: "Weber® Q 3200 Gas Grill (Natural Gas)",
      category: "Portable",
      price: 22.99,
      img: "./assets/GasGrills/grill11.png",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 12,
      title: "Weber® Q 1200 Gas Grill",
      category: "Portable",
      price: 22.99,
      img: "./assets/GasGrills/grill12.png",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    ];